alias agi="sudo apt-get install"
alias agu="sudo apt-get update"
alias agr="sudo apt-get remove"
alias music="bash /home/satyarth/.scripts/music.sh"
alias sunny="bash /home/satyarth/.scripts/sunny.sh"
